"""Shared constants for the chain-only Ableton MCP harness."""

from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[1]
SCHEMA_PATH = PROJECT_ROOT / "schema" / "seed_actions.json"

DEFAULT_BRIDGE_SOCKET_PATH = "/tmp/ableton_chain_bridge.sock"
DEFAULT_GATEWAY_HOST = "127.0.0.1"
DEFAULT_GATEWAY_PORT = 8001

ROUTE_API = "api"
ROUTE_BRIDGE = "bridge"

ERROR_ABLETON_UNAVAILABLE = "ABLETON_UNAVAILABLE"
ERROR_BRIDGE_UNAVAILABLE = "BRIDGE_UNAVAILABLE"
ERROR_TRANSPORT_TIMEOUT = "TRANSPORT_TIMEOUT"
ERROR_INVALID_ACTION_PAYLOAD = "INVALID_ACTION_PAYLOAD"
ERROR_UNSUPPORTED_ACTION = "UNSUPPORTED_ACTION"
ERROR_GATEWAY_INCOMPATIBLE = "GATEWAY_INCOMPATIBLE"
ERROR_INTERNAL = "INTERNAL_ERROR"

HEALTH_STARTING = "starting"
HEALTH_CONNECTING = "connecting"
HEALTH_READY = "ready"
HEALTH_DEGRADED = "degraded"

BRIDGE_HEARTBEAT_INTERVAL_SEC = 2.0
BRIDGE_HEARTBEAT_MISSES_BEFORE_RESTART = 3
BRIDGE_RESTART_BUDGET_COUNT = 5
BRIDGE_RESTART_BUDGET_WINDOW_SEC = 300
BRIDGE_RESTART_CIRCUIT_BREAK_SEC = 60

API_DEFAULT_TIMEOUT_MS = 3000
API_MAX_TIMEOUT_MS = 7000

READ_ONLY_ACTIONS = {
    "inspect_track_chain",
}

REQUIRED_GATEWAY_ACTIONS = {
    "build_device_chain",
    "update_device_parameters",
    "inspect_track_chain",
}

GATEWAY_HEALTH_EQUIVALENTS = {
    "health_check",
    "ping",
}
